### ISSUE TITLE
please transpile to es5 its breaking ie11

### ISSUE THREAD

**Issue by JiniHendrix** [moxystudio/js-keyboard-only-outlines#18]
please

**Comment by satazor** [comment]
As stated in the README, you should transpile it yourself. If you are using Webpack, just include it `require.resolve('keyboard-only-outlines)' in the `include` array of the rule using babel.

> This library is written in modern JavaScript and is published in both CommonJS and ES module transpiled variants. If you target older browsers please make sure to transpile accordingly.
