### ISSUE TITLE
Make accepted codes an array

### ISSUE THREAD

**Issue by satazor** [moxystudio/js-keyboard-only-outlines#3]
https://github.com/moxystudio/js-keyboard-only-outlines/blob/master/index.js#L6

This could be simply an array, where each entry could have a comment saying the key it is.
This would avoid the necessity of having to the `Object.keys()` on every keystroke.

**Comment by acostalima** [comment]
I mentioned yesterday `Object.keys()` could be cached, but I guess that works too. 😄
